export { default as Settings } from "../assets/svg/settings.svg";
export { default as Logout } from "../assets/svg/logout.svg";
export { default as Folder } from "../assets/svg/folder.svg";
export { default as Arrow } from "../assets/svg/arrow.svg";
export { default as Add } from "../assets/svg/add.svg";
export { default as Erase } from "../assets/svg/erase.svg";
export { default as Edit } from "../assets/svg/edit.svg";
export { default as Logo } from "../assets/images/Logo.png";
export { default as TaskFill } from "../assets/images/taskFill.png";
